<table>
  <tr>
    <th style="background-color:#ffe694;">
     
<font size=6> Les tableaux uni et multi-dimentionnels (1)</font>
      </th>
  </tr>
</table>

## Le module <font color='blue'>numpy</font> contient les éléments nécessaires pour manipuler <font color='green'>vecteurs</font>, <font color='green'>matrices</font>, et tableaux de <font color='green'>dimension supérieure</font>.


In [2]:
import numpy as np

## Définition d'un tableau

In [3]:
vec = np.array([1,7,3])
vec

In [6]:
mat = np.array([[2,0,3], [4,-7,1], [-5,1,-8], [0,2,0]])
mat

## Premières propriétés d'un tableau

In [8]:
mat.shape

In [9]:
nbl = mat.shape[0]
nbc = mat.shape[1]
print('La matrice a ',nbl,' lignes et ',nbc,' colonnes.')

In [10]:
sz = mat.size
sz

In [11]:
nd = mat.ndim
nd

## Accéder aux éléments d'un tableau

In [25]:
#Calcul de la somme des éléments de la matrice
s = 0
for i in range(nbl):
  for j in range(nbc):
    s = s+mat[i,j]
    
print('Somme des éléments de la matrice = ',s)

Somme des éléments de la matrice =  -7


In [26]:
#Remplacer tous les éléments négatifs à un seuil par 0
for i in range(nbl):
  for j in range(nbc):
    if mat[i,j]<0:
      mat[i,j]=0.0
    
mat

array([[2, 0, 3],
       [4, 0, 1],
       [0, 1, 0],
       [0, 2, 0]])

In [27]:
#Extraction d'un colonne
vl = mat[1]
vl

array([4, 0, 1])

In [28]:
#Extraction d'un colonne
vc = mat[:,2]
vc

array([3, 1, 0, 0])

In [11]:
#Plus généralement extraction d'un sous-tableau
st1 = mat[0:3,0:2]
st1

array([[2, 0],
       [4, 0],
       [0, 1]])

In [12]:
#On peut aussi extraire des lignes ou des colonnes non consécutives
st2 = mat[[0,2,3],:]

In [13]:
st2

array([[2, 0, 3],
       [0, 1, 0],
       [0, 2, 0]])

## Création de tableaux particuliers (identité, tableaux de 1, tableau de 0)

In [14]:
I = np.identity(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
mat0 = np.zeros([3,4])
mat0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
mat1 = np.ones([2,3])
mat1

array([[1., 1., 1.],
       [1., 1., 1.]])

## Création de tableaux de nombres aléatoires: Voir [ce chapitre](forRandom.ipynb)

## Création d'un tableau à partir d'un fichier texte

In [35]:
tab1 = np.loadtxt('data\\dataset1.txt')
nbl = tab1.shape[0]
nbc = tab1.shape[1]
print('Le tableau lu contient ',nbl*nbc,' valeurs réparties sur ',nbl,' lignes et ',nbc,' colonnes')

Le tableau lu contient  25137  valeurs réparties sur  1197  lignes et  21  colonnes


### La fonction <font color='blue'>loadtxt</font> a plusieurs paramètres. Dans l'instruction précédente, nous avons pris les valeurs par défaut de tous les paramètres, notamment le séparateur (pris égal à l'espace). Dans l'instruction suivante, nous modifions les valeurs des paramètres <font color='blue'>skiprows</font> (pour éviter de lire l'entête), <font color='blue'>delimiter</font>, et <font color='blue'>usecols</font> (seuls les 4 colonnes numériques nous intéressent).

In [38]:
tab2 = np.loadtxt('data\\iris.csv', skiprows=1, delimiter=',', usecols=(0,1,2,3))
nbo = tab2.shape[0]
nbv = tab2.shape[1]
print('Le dataset Iris est composé de ',nbv,' variables et ',nbo,' observations.')

Le dataset iris est compsé de  4  variables et  150  observations.


## La suite de ce chapitre est [ici](forArrays2.ipynb)