<table>
  <tr>
    <th style="background-color:#ffe694;">
     
<font size=6> Les tableaux uni et multi-dimentionnels (2)</font>
      </th>
  </tr>
</table>

## La première partie de ce chapitre est [ici](forArrays.ipynb)


In [22]:
import numpy as np

mat1 = np.array([[2,0,3], [4,-7,1], [-5,1,-8], [0,2,0]])
mat2 = np.array([[0,-1,1], [1,-3,0], [2,-1,-1], [2,0,1]])

## Opérations sur les tableaux. Pour commencer, lorsque deux tableaux ont la même dimension on peut leur appliquer les opérations  <font color='green'>élement par élément</font>.


In [23]:
s_mat = mat1+mat2
p_mat = mat1*mat2

p_mat

array([[  0,   0,   3],
       [  4,  21,   0],
       [-10,  -1,   8],
       [  0,   0,   0]])

## Il y a ensuite <font color='green'>les opérations algébriques</font>.

In [24]:
#Transposition d'une matrice
t_mat1 = mat1.transpose()
t_mat1

array([[ 2,  4, -5,  0],
       [ 0, -7,  1,  2],
       [ 3,  1, -8,  0]])

In [25]:
#Produit matrice-vecteur
vect = np.array([1,1,1])
pmv = np.dot(mat1, vect)

In [26]:
#Produit scalaire de deux vecteurs
vect1 = np.array([1,1,1])
vect2 = np.array([2,-1,2])

ps = np.dot(vect1, vect2)
ps

3

In [27]:
#Produit matriciel
mat3 = np.random.rand(4,3)
mat4 = np.random.rand(3,5)

pm = np.dot(mat3, mat4)
pm

array([[0.42951458, 0.31047993, 0.39272704, 0.53222392, 0.5145083 ],
       [0.36248656, 0.45977779, 0.58254984, 0.51892454, 0.60414784],
       [0.12238305, 0.23318771, 0.30683945, 0.1651603 , 0.28836673],
       [0.68837577, 0.75177496, 0.99339774, 0.8040603 , 1.10726125]])

In [28]:
pm.shape

(4, 5)