<table>
  <tr>
    <th style="background-color:#ffe694;">
     
<font size=6> Manipulation des nombres aléatoires</font>
      </th>
  </tr>
</table>

## Deux modules Python permettent de manipuler des nombres aléatoires: <font color='blue'>random</font> et <font color='blue'>numpy</font>.

# <u> Commençons par le module  <font color='blue'>random</font></u>

In [1]:
import random

In [2]:
#Générer un nombre aléatoire compris entre 0 et 1.
rnd = random.random()
rnd

0.40188498375317905

In [3]:
#Générer un entier compris entre n1 et n2-1 (compris)
rndi = random.randint(1,10)
rndi

7

In [4]:
#Idem mais en ajoutant un pas (step) se fait de la manière suivante:
rndr = random.randrange(0,101,5)
rndr

30

In [5]:
#Sélectionner un ou plusieurs éléments (avec remise) dans une liste avec des probabilités éventuellement différentes. On notera
#que dans le cas de plusieurs éléments est une liste. 
l = ['e1', 'e2', 'e3', 'e4', 'e5']
chc = random.choice(l)
chc

'e5'

In [6]:
chcs1 = random.choices(l,k=3)
chcs1

['e3', 'e1', 'e4']

In [7]:
chcs2 = random.choices(l,k=10)
chcs2

['e4', 'e3', 'e1', 'e4', 'e5', 'e4', 'e5', 'e3', 'e3', 'e3']

In [8]:
chcs3 = random.choices(l, k=10, weights=(2, 2, 1, 1, 1))
chcs3

['e1', 'e2', 'e4', 'e2', 'e2', 'e1', 'e5', 'e3', 'e5', 'e1']

In [9]:
# On peut aussi imposer à la liste des éléments sélections d'être un échantillon de la liste du départ, i.e. une liste de 
#plus petite taille, sans répatition
smp = random.sample(l, k=2) 
smp

['e5', 'e2']

In [10]:
#La fonction permute aléatoirement les éléments d'une liste
random.shuffle(l)
l

['e2', 'e3', 'e5', 'e4', 'e1']

# <u> Passons à présent au module  <font color='blue'>numpy</font></u>

In [11]:
import numpy as np

## La première remarque qu'on peut faire est que l'on retrouve dans <font color='blue'>numpy</font></u> des fonctions qui ont le même nom que celles de <font color='blue'>random</font></u> présentées ci-dessus. Ce que ces fonctions apportent de plus est qu'elles génèrent un tableau de valeurs plutôt qu'une seule. Les exemples suivants permettent de l'illustrer.

In [12]:
# La fonction suivante prend 0 ou 1 argument. Elle retourne donc une valeur ou un tableau de valeurs à une seule dimension.
tab0 = np.random.random(5)
tab0

array([0.09987959, 0.00096187, 0.79988372, 0.25054924, 0.19852194])

In [13]:
# La fonction suivante peut retourner un tableau à plusieurs dimensions.
tab1 = np.random.rand(10)
tab1

array([0.83368056, 0.36087849, 0.29421219, 0.36861672, 0.57559539,
       0.60200515, 0.73164171, 0.9565716 , 0.36284625, 0.28126814])

In [14]:
tab2 = np.random.rand(3,4,5)
tab2

array([[[0.32670556, 0.98615174, 0.86576594, 0.25661862, 0.97701893],
        [0.68301513, 0.06209606, 0.42334631, 0.29883413, 0.89655858],
        [0.43676009, 0.27398093, 0.72130774, 0.63069038, 0.17471168],
        [0.22907276, 0.03596554, 0.29126136, 0.69077576, 0.54954294]],

       [[0.1277811 , 0.68084991, 0.38752136, 0.00859285, 0.05251456],
        [0.84716894, 0.24293283, 0.45725155, 0.19641394, 0.46823834],
        [0.17756842, 0.64620583, 0.23801158, 0.55750447, 0.67938472],
        [0.31387131, 0.97982031, 0.96868263, 0.3068696 , 0.13093709]],

       [[0.34038937, 0.67044079, 0.66522815, 0.87393301, 0.80819427],
        [0.03760646, 0.66655785, 0.66189404, 0.64114006, 0.00504794],
        [0.89778817, 0.50833434, 0.60150304, 0.54655709, 0.49623407],
        [0.01450398, 0.32583039, 0.27081554, 0.89190577, 0.55114005]]])

In [15]:
tab3 = np.random.randint(1,10,[5,3])
tab3

array([[8, 1, 2],
       [8, 2, 1],
       [5, 1, 5],
       [2, 4, 6],
       [2, 1, 6]])

In [16]:
tab4 = np.random.choice(range(10), 10, replace=True)
tab4

array([8, 2, 6, 3, 7, 2, 0, 1, 5, 2])

## La fonction <font color='blue'>shuffle</font> s'applique aux listes, aux tableaux et à d'autres structures de données.

In [17]:
tab5 = np.array([[6, 1, 7],
       [1, 7, 6],
       [6, 6, 2],
       [8, 9, 6],
       [8, 8, 7]])
np.random.shuffle(tab5)
tab5

array([[8, 8, 7],
       [8, 9, 6],
       [1, 7, 6],
       [6, 1, 7],
       [6, 6, 2]])

## La fonction <font color='blue'>permutation</font> prend en entrée un entier strictement positif ou une liste.

In [20]:
p1=np.random.permutation(5)
p1

array([1, 0, 4, 2, 3])

In [22]:
p2 = np.random.permutation([8, 1, 4, 7, 5])
p2

array([4, 7, 1, 8, 5])

# <u> Manipulation des  <font color='red'>distributions</font> de probabilités</u> 

## Il est possible de générer des nombres aléatoires obéissant à une distribution de probabilité donnée en utilisant <font color='blue'>random</font> ou <font color='blue'>numpy.random</font>. L'avantage de ce dernier étant de pouvoir générer des tableaux plutôt que des valeurs individuelles. 

In [23]:
tabu = np.random.uniform(0, 1, (4, 3))
tabu

array([[0.38591381, 0.66259315, 0.70981118],
       [0.20884545, 0.85540729, 0.67255721],
       [0.75847589, 0.28092187, 0.12408421],
       [0.16015738, 0.04155343, 0.48799717]])

# <u> Récapitulatif des mots réservés</u>: 
## <font color='blue'>random</font>, <font color='blue'>randint</font>, <font color='blue'>randrange</font>, <font color='blue'>choice</font>, <font color='blue'>rand</font>, <font color='blue'>shuffle</font>,


# <u> Exercices</u>
1. (Bootstrapping)
2. (Estimation du nombre Pi par la méthode de Monte-Carlo)
3. (Initialisation des poids d'un réseau de neurones)